In [5]:
import torch
import torch.nn as nn

In [6]:
input = torch.randn(3, 3)
input

tensor([[-0.1530,  0.5203, -0.1237],
        [ 0.5116, -1.1695,  1.1804],
        [-1.3874, -0.5575, -0.7707]])

In [7]:
target = torch.Tensor([0, 2, 1])
target = target.to(int)
target

tensor([0, 2, 1])

In [8]:
import torch.nn.functional as F

In [19]:
sm = nn.Softmax(dim=1)
s = sm(input)
s

tensor([[0.2506, 0.4913, 0.2581],
        [0.3187, 0.0593, 0.6220],
        [0.1943, 0.4456, 0.3601]])

In [10]:
l = torch.log(s)
l

tensor([[-1.3839, -0.7106, -1.3546],
        [-1.1436, -2.8247, -0.4748],
        [-1.6382, -0.8083, -1.0215]])

In [11]:
ls = nn.LogSoftmax(dim=1)(input)
ls

tensor([[-1.3839, -0.7106, -1.3546],
        [-1.1436, -2.8247, -0.4748],
        [-1.6382, -0.8083, -1.0215]])

In [12]:
F.nll_loss(l, target)

tensor(0.8890)

In [13]:
F.nll_loss(s, target)

tensor(-0.4394)

In [14]:
nn.CrossEntropyLoss()(input, target)

tensor(0.8890)

In [15]:
nn.CrossEntropyLoss()(s, target)

tensor(1.0053)

In [16]:
import numpy as np

arr = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])

print(arr[1, 1:4])

[7 8 9]


In [17]:
np.arange(5)

array([0, 1, 2, 3, 4])